version: "3.7"
services:
  src-simulator-server:
    image: simulator-server
    container_name: src-simulator-server
    environment:
      - PORT=1212
      - KUBE_SCHEDULER_SIMULATOR_ETCD_URL=http://src-simulator-cluster:2379
      - KUBE_APISERVER_URL=http://src-simulator-cluster:3131
    volumes:
      - ./src-config.yaml:/config.yaml
      - ./src-kubeconfig.yaml:/kubeconfig.yaml
    ports:
      - "1212:1212"
    restart: always
    tty: true
    networks:
      - simulator-internal-network
  src-simulator-frontend:
    image: simulator-frontend
    restart: always
    container_name: src-simulator-frontend
    environment:
      - HOST=0.0.0.0
      - BASE_URL=http://${SIMULATOR_EXTERNAL_IP:-localhost}:1212
      - KUBE_API_SERVER_URL=http://${SIMULATOR_EXTERNAL_IP:-localhost}:3131
    ports:
    - "3000:3000"
    tty: true
  src-simulator-cluster:
    image: registry.k8s.io/kwok/cluster:v0.6.0-k8s.v1.30.2
    container_name: src-simulator-cluster
    restart: always
    ports:
      - "3131:3131"
    volumes:
      - simulator-etcd-data:/var/lib/etcd
      - ./kwok.yaml:/root/.kwok/kwok.yaml
    environment:
      - KWOK_KUBE_APISERVER_PORT=3131
    networks:
      - simulator-internal-network
  dst-simulator-server:
    image: simulator-server
    container_name: dst-simulator-server
    environment:
      - PORT=1213
      - KUBE_SCHEDULER_SIMULATOR_ETCD_URL=http://dst-simulator-cluster:2379
      - KUBE_APISERVER_URL=http://dst-simulator-cluster:3132
    volumes:
      - ./dst-config.yaml:/config.yaml
      - ./dst-kubeconfig.yaml:/kubeconfig.yaml
    ports:
      - "1213:1213"
    restart: always
    tty: true
    networks:
      - simulator-internal-network
  dst-simulator-frontend:
    image: simulator-frontend
    restart: always
    container_name: dst-simulator-frontend
    environment:
      - HOST=0.0.0.0
      - PORT=3001
      - BASE_URL=http://${SIMULATOR_EXTERNAL_IP:-localhost}:1213
      - KUBE_API_SERVER_URL=http://${SIMULATOR_EXTERNAL_IP:-localhost}:3132
    ports:
    - "3001:3001"
    tty: true
  dst-simulator-cluster:
    image: registry.k8s.io/kwok/cluster:v0.6.0-k8s.v1.30.2
    container_name: dst-simulator-cluster
    restart: always
    ports:
      - "3132:3132"
    volumes:
      - simulator-etcd-data:/var/lib/etcd
      - ./kwok.yaml:/root/.kwok/kwok.yaml
    environment:
      - KWOK_KUBE_APISERVER_PORT=3132
    networks:
      - simulator-internal-network
networks:
  simulator-internal-network:
    driver: bridge
volumes:
  simulator-etcd-data:
