version: "3.7"
services:
  simulator-server:
    image: simulator-server
    container_name: simulator-server
    environment:
      - PORT=1212
      - KUBE_SCHEDULER_SIMULATOR_ETCD_URL=http://simulator-cluster:2379
      - KUBE_APISERVER_URL=http://simulator-cluster:3131
    volumes:
      - ./simulator/config.yaml:/config.yaml
      - ./simulator/kubeconfig.yaml:/kubeconfig.yaml
    ports:
      - "1212:1212"
    restart: always
    tty: true
    extra_hosts:
      - kind-control-plane:host-gateway
    networks:
      - simulator-internal-network
  simulator-frontend:
    image: simulator-frontend
    restart: always
    container_name: simulator-frontend
    environment:
      - HOST=0.0.0.0
      - BASE_URL=http://${SIMULATOR_EXTERNAL_IP:-localhost}:1212
      - KUBE_API_SERVER_URL=http://${SIMULATOR_EXTERNAL_IP:-localhost}:3131
    ports:
    - "3000:3000"
    tty: true
  simulator-cluster:
    image: registry.k8s.io/kwok/cluster:v0.6.0-k8s.v1.30.2
    container_name: simulator-cluster
    restart: always
    ports:
      - "3131:3131"
    volumes:
      - simulator-etcd-data:/var/lib/etcd
      - ./kwok.yaml:/root/.kwok/kwok.yaml
    environment:
      - KWOK_KUBE_APISERVER_PORT=3131
    networks:
      - simulator-internal-network
  simulator-server-2:
    image: simulator-server
    container_name: simulator-server-2
    environment:
      - PORT=1213
      - KUBE_SCHEDULER_SIMULATOR_ETCD_URL=http://simulator-cluster-2:2379
      - KUBE_APISERVER_URL=http://simulator-cluster-2:3132
      - CORS_ALLOWED_ORIGIN_LIST=http://localhost:3001
    volumes:
      - ./simulator/config.yaml:/config.yaml
      - ./simulator/kubeconfig.yaml:/kubeconfig.yaml
    ports:
      - "1213:1213"
    restart: always
    tty: true
    extra_hosts:
      - kind-control-plane:host-gateway
    networks:
      - simulator-internal-network
  simulator-frontend-2:
    image: simulator-frontend
    restart: always
    container_name: simulator-frontend-2
    environment:
      - HOST=0.0.0.0
      - PORT=3001
      - BASE_URL=http://${SIMULATOR_EXTERNAL_IP:-localhost}:1213
      - KUBE_API_SERVER_URL=http://${SIMULATOR_EXTERNAL_IP:-localhost}:3132
    ports:
    - "3001:3001"
    tty: true
  simulator-cluster-2:
    image: registry.k8s.io/kwok/cluster:v0.6.0-k8s.v1.30.2
    container_name: simulator-cluster-2
    restart: always
    ports:
      - "3132:3132"
    volumes:
      - simulator-etcd-data:/var/lib/etcd
      - ./kwok.yaml:/root/.kwok/kwok.yaml
    environment:
      - KWOK_KUBE_APISERVER_PORT=3132
    networks:
      - simulator-internal-network
networks:
  simulator-internal-network:
    driver: bridge
volumes:
  simulator-etcd-data:
